# Generated by Django 2.2.4 on 2020-06-26 19:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, 'the password must have at least 8 characters')])),
                ('last_login', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
