# Generated by Django 2.2.4 on 2020-07-04 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200704_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.GenericIPAddressField(null=True, validators=[django.core.validators.validate_ipv4_address])),
                ('status', models.BooleanField(default=False)),
                ('env', models.CharField(choices=[('Produção', 'Produção'), ('Homologação', 'Homologação'), ('Desenvolvimento', 'Desenvolvimento')], max_length=20)),
                ('version', models.CharField(max_length=5)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
