# Generated by Django 2.2.4 on 2020-07-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='env',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='version',
        ),
    ]
