# Generated by Django 2.2.4 on 2020-07-06 22:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200706_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.GenericIPAddressField(null=True, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AddField(
            model_name='agent',
            name='env',
            field=models.CharField(choices=[('Produção', 'Produção'), ('Homologação', 'Homologação'), ('Desenvolvimento', 'Desenvolvimento')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.User'),
        ),
        migrations.AddField(
            model_name='agent',
            name='version',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
