# Generated by Django 2.2.4 on 2020-07-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200706_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'critical.'), ('debug', 'debug'), ('warning', 'warning'), ('information', 'info')], max_length=20)),
                ('data', models.TextField(max_length=500)),
                ('arquivado', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Agent')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
