# Generated by Django 2.2.4 on 2020-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200715_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
