# Generated by Django 2.2.4 on 2020-07-15 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200715_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='env',
        ),
        migrations.AddField(
            model_name='event',
            name='env',
            field=models.CharField(choices=[('Produção', 'Produção'), ('Homologação', 'Homologação'), ('Desenvolvimento', 'Desenvolvimento')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
